---
- name: Deploy Spring Boot Application with Apache2
  hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Copy JAR file to deployment directory
      copy:
        src: target/mitech.jar  # Adjust the source path if needed
        dest: /var/www/html/mitech.jar
        mode: 0644  # Set appropriate file permissions

    - name: Configure Apache2 to serve the JAR file
      template:
        src: apache2-site.conf.j2  # Create a Jinja2 template for Apache2 configuration
        dest: /etc/apache2/sites-available/mitech.conf
        owner: root
        group: root
        mode: '0644'
      notify:
        - Reload Apache2

    - name: Enable Apache2 site
      apache2_module:
        state: present
        name: rewrite
      command: a2ensite mit
      notify:
        - Restart Apache2

    - name: Disable default Apache2 site
      apache2_module:
        state: absent
        name: rewrite
      command: a2dissite 000-default
      notify:
        - Reload Apache2

    - name: Open port 80 in UFW
      ufw:
        rule: allow
        port: 80
        proto: tcp

  handlers:
    - name: Reload Apache2
      systemd:
        name: apache2
        state: reloaded

    - name: Restart Apache2
      systemd:
        name: apache2
        state: restarted
