---
- name: Install and configure Apache Tomcat
  hosts: localhost
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install default-jdk
      apt:
        name: default-jdk
        state: present

    - name: Create tomcat user
      user:
        name: tomcat
        home: /opt/tomcat
        system: yes

    - name: Download and extract Tomcat
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-9/v9.0.55/bin/apache-tomcat-9.0.55.tar.gz"
        dest: /tmp/apache-tomcat.tar.gz

    - name: Extract Tomcat
      unarchive:
        src: /tmp/apache-tomcat.tar.gz
        dest: /opt/tomcat
        remote_src: yes

    - name: Create symbolic link for latest Tomcat version
      file:
        src: /opt/tomcat/apache-tomcat-9.0.55
        dest: /opt/tomcat/latest
        state: link

    - name: Set ownership and permissions
      file:
        path: /opt/tomcat/latest
        recurse: yes
        owner: tomcat
        group: tomcat

    - name: Configure Tomcat systemd service
      copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service

    - name: Start and enable Tomcat service
      systemd:
        name: tomcat
        enabled: yes
        state: started

    - name: Open ports 80 and 8080 in firewall
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - 80
        - 8080

    - name: Copy mitech.war to Tomcat webapps
      copy:
        src: mitech.war
        dest: /opt/tomcat/latest/webapps/

    - name: Reload UFW
      systemd:
        name: ufw
        state: restarted
