---
- name: Install and configure Apache Tomcat
  hosts: localhost
  become: yes
  vars:
    # Setting this for unarchive to work
    ansible_remote_tmp: /tmp


  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install default-jdk
      apt:
        name: default-jdk
        state: present
        
    - name: Create Tomcat directory
      file:
        path: /opt/tomcat
        state: directory
        mode: '0755'
              
    - name: Create tomcat user
      user:
        name: tomcat
        home: /opt/tomcat
        system: yes

    - name: Download Tomcat
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.12/bin/apache-tomcat-10.1.12.tar.gz"
        dest: /tmp/apache-tomcat.tar.gz

    - name: Unzip Tomcat tarball
      command: "tar xzvf /tmp/apache-tomcat.tar.gz -C /opt/tomcat --strip-components=1"


    - name: Create symbolic link for latest Tomcat version
      file:
        src: /opt/tomcat
        dest: /opt/tomcat/latest
        state: link

    - name: Set ownership and permissions
      file:
        path: /opt/tomcat/latest
        owner: tomcat
        group: tomcat

    - name: Configure Tomcat systemd service
      copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service

    - name: Start and enable Tomcat service
      systemd:
        name: tomcat
        enabled: yes
        state: started

    - name: Open ports 80 and 8080 in firewall
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - 80
        - 8080

    - name: Copy mitech.war to Tomcat webapps
      copy:
        src: mitech.war
        dest: /opt/tomcat/latest/webapps/

    - name: Reload UFW
      systemd:
        name: ufw
        state: restarted
