---
- name: Install and configure Apache2 with Reverse Proxy
  hosts: localhost
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Enable Apache2 modules
      apache2_module:
        name: "{{ item }}"
        state: present
      with_items:
        - proxy
        - proxy_http
        - proxy_html
        - proxy_wstunnel
        - rewrite

    - name: Copy Apache2 site configuration
      copy:
        src: apache2-site.conf
        dest: /etc/apache2/sites-available/apache2-site.conf

    - name: Disable default Apache2 site
      apache2_module:
        name: 000-default
        state: absent

    - name: Enable Apache2 site
      command: a2ensite apache2-site

    - name: Reload Apache2 service
      service:
        name: apache2
        state: reloaded
